import { User, Bounty, Achievement, Challenge, LeaderboardEntry } from '@/types';

// Sample achievements
export const ACHIEVEMENTS: Achievement[] = [
    { id: 'first_cleanup', name: 'First Sweep', description: 'Complete your first cleanup', icon: '🧹' },
    { id: 'ten_cleanups', name: 'Street Cleaner', description: 'Complete 10 cleanups', icon: '🌟' },
    { id: 'fifty_cleanups', name: 'Neighborhood Hero', description: 'Complete 50 cleanups', icon: '🏆' },
    { id: 'first_bounty', name: 'Scout', description: 'Create your first bounty', icon: '🔍' },
    { id: 'high_roller', name: 'High Roller', description: 'Complete a 500+ coin bounty', icon: '💎' },
    { id: 'speed_demon', name: 'Speed Demon', description: 'Complete a bounty within 1 hour', icon: '⚡' },
    { id: 'perfectionist', name: 'Perfectionist', description: 'Get 10 verified cleanups', icon: '✨' },
    { id: 'weekly_warrior', name: 'Weekly Warrior', description: 'Complete all weekly challenges', icon: '🗡️' },
];

// Sample user
export const MOCK_USER: User = {
    user_id: 'user_001',
    email: 'player@sweepx.io',
    username: 'CleanMachine',
    avatar_url: '',
    xp: 2450,
    level: 12,
    reputation: 95,
    achievements: [
        { ...ACHIEVEMENTS[0], unlockedAt: '2024-01-15T10:00:00Z' },
        { ...ACHIEVEMENTS[1], unlockedAt: '2024-02-20T14:30:00Z' },
        { ...ACHIEVEMENTS[3], unlockedAt: '2024-01-18T09:00:00Z' },
    ],
    cleanups_completed: 28,
    bounties_created: 15,
    coins: 1250,
    created_at: '2024-01-10T08:00:00Z',
};

// Sample bounties with real-world coordinates
export const MOCK_BOUNTIES: Bounty[] = [
    {
        bounty_id: 'bounty_001',
        creator_id: 'user_002',
        creator_username: 'CityWatcher',
        image_url: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=400',
        latitude: 28.6139,
        longitude: 77.2090,
        location_name: 'Connaught Place, Delhi',
        dirt_level: 3,
        bounty_amount: 150,
        status: 'open',
        created_at: '2024-12-27T10:00:00Z',
    },
    {
        bounty_id: 'bounty_002',
        creator_id: 'user_003',
        creator_username: 'GreenPatrol',
        image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
        latitude: 28.5355,
        longitude: 77.3910,
        location_name: 'Sector 18, Noida',
        dirt_level: 4,
        bounty_amount: 300,
        status: 'open',
        created_at: '2024-12-26T15:30:00Z',
    },
    {
        bounty_id: 'bounty_003',
        creator_id: 'user_004',
        creator_username: 'EcoHunter',
        image_url: 'https://images.unsplash.com/photo-1526951521990-620dc14c214b?w=400',
        latitude: 28.4595,
        longitude: 77.0266,
        location_name: 'DLF Cyber City, Gurugram',
        dirt_level: 2,
        bounty_amount: 75,
        status: 'open',
        created_at: '2024-12-27T08:15:00Z',
    },
    {
        bounty_id: 'bounty_004',
        creator_id: 'user_001',
        creator_username: 'CleanMachine',
        cleaner_id: 'user_005',
        cleaner_username: 'SweepMaster',
        image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
        proof_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
        latitude: 28.6304,
        longitude: 77.2177,
        location_name: 'India Gate, Delhi',
        dirt_level: 5,
        bounty_amount: 500,
        status: 'completed',
        created_at: '2024-12-20T12:00:00Z',
        completed_at: '2024-12-21T16:00:00Z',
    },
    {
        bounty_id: 'bounty_005',
        creator_id: 'user_006',
        creator_username: 'UrbanCleaner',
        image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400',
        latitude: 28.5494,
        longitude: 77.2001,
        location_name: 'Hauz Khas Village, Delhi',
        dirt_level: 3,
        bounty_amount: 200,
        status: 'accepted',
        cleaner_id: 'user_001',
        cleaner_username: 'CleanMachine',
        created_at: '2024-12-25T09:00:00Z',
    },
];

// Sample challenges
export const MOCK_CHALLENGES: Challenge[] = [
    {
        id: 'daily_1',
        title: 'Quick Sweep',
        description: 'Complete 1 cleanup today',
        xp_reward: 50,
        coin_reward: 25,
        target: 1,
        progress: 0,
        type: 'daily',
        expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'daily_2',
        title: 'Bounty Hunter',
        description: 'Accept 2 bounties',
        xp_reward: 30,
        coin_reward: 15,
        target: 2,
        progress: 1,
        type: 'daily',
        expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'weekly_1',
        title: 'Street Guardian',
        description: 'Complete 10 cleanups this week',
        xp_reward: 500,
        coin_reward: 250,
        target: 10,
        progress: 3,
        type: 'weekly',
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

// Sample leaderboard
export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
    { rank: 1, user_id: 'user_100', username: 'EcoWarrior', avatar_url: '', xp: 15000, level: 35, cleanups_completed: 156 },
    { rank: 2, user_id: 'user_101', username: 'CleanKing', avatar_url: '', xp: 12500, level: 30, cleanups_completed: 132 },
    { rank: 3, user_id: 'user_102', username: 'GreenNinja', avatar_url: '', xp: 10200, level: 26, cleanups_completed: 98 },
    { rank: 4, user_id: 'user_103', username: 'SweepLord', avatar_url: '', xp: 8900, level: 23, cleanups_completed: 87 },
    { rank: 5, user_id: 'user_104', username: 'DustBuster', avatar_url: '', xp: 7500, level: 21, cleanups_completed: 76 },
    { rank: 6, user_id: 'user_001', username: 'CleanMachine', avatar_url: '', xp: 2450, level: 12, cleanups_completed: 28 },
    { rank: 7, user_id: 'user_105', username: 'StreetHero', avatar_url: '', xp: 2100, level: 11, cleanups_completed: 25 },
    { rank: 8, user_id: 'user_106', username: 'TrashTerminator', avatar_url: '', xp: 1800, level: 10, cleanups_completed: 21 },
    { rank: 9, user_id: 'user_107', username: 'CleanQueen', avatar_url: '', xp: 1500, level: 9, cleanups_completed: 18 },
    { rank: 10, user_id: 'user_108', username: 'EcoChamp', avatar_url: '', xp: 1200, level: 8, cleanups_completed: 15 },
];
